// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNm1QFKgIsXkZiHpCTH8ZTBbTRz5RG3SI',
    appId: '1:493444618231:android:d772688e6c937eec3fc0f2',
    messagingSenderId: '493444618231',
    projectId: 'eshop-ca7f0',
    databaseURL: 'https://eshop-ca7f0-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-ca7f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb4h0uIyW3oa2ltgbGV-4T3tp1VxLmHvM',
    appId: '1:493444618231:ios:aa8262d0c33b40953fc0f2',
    messagingSenderId: '493444618231',
    projectId: 'eshop-ca7f0',
    databaseURL: 'https://eshop-ca7f0-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-ca7f0.appspot.com',
    iosBundleId: 'com.example.lesson73',
  );

}